# Generated by Django 4.2.3 on 2023-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("user_type", models.CharField(max_length=100)),
                ("user_category", models.CharField(max_length=100)),
                ("user_location", models.CharField(max_length=100)),
                ("analyzed_text", models.TextField()),
            ],
        ),
    ]
