# Generated by Django 4.2.3 on 2023-08-18 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="imporoved_text",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
