# Generated by Django 4.2.3 on 2023-08-18 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_analysisresult_imporoved_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisresult",
            old_name="imporoved_text",
            new_name="improved_text",
        ),
    ]
