# Generated by Django 4.2.3 on 2023-09-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_imporoved_text_analysisresult_improved_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('analyzed_answer', models.TextField()),
            ],
        ),
    ]
