# Generated by Django 4.2.3 on 2023-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_admintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='reference_urls',
            field=models.JSONField(default=list),
        ),
    ]
